const packageData = [
  {
    area: "Coverage",
    country: "Canada",
    flag: "https://i.ibb.co/5WNh9wm/bd-Country-Flag.png",
    data: "2GB",
    validity: "10 days",
    price: 5.6,
    facilities: ["Data Only", "No Contracts", "No SIM Cards"],
  },
  {
    area: "Coverage",
    country: "Canada",
    flag: "https://i.ibb.co/5WNh9wm/bd-Country-Flag.png",
    data: "5GB",
    validity: "15 days",
    price: 9.9,
    facilities: ["Data Only", "No Contracts", "No SIM Cards"],
  },
  {
    area: "Coverage",
    country: "Canada",
    flag: "https://i.ibb.co/5WNh9wm/bd-Country-Flag.png",
    data: "10GB",
    validity: "30 days",
    price: 15.2,
    facilities: ["Data Only", "No Contracts", "No SIM Cards"],
  },
  {
    area: "Coverage",
    country: "Canada",
    flag: "https://i.ibb.co/5WNh9wm/bd-Country-Flag.png",
    data: "15GB",
    validity: "30 days",
    price: 22.5,
    facilities: ["Data Only", "No Contracts", "No SIM Cards"],
  },
  {
    area: "Coverage",
    country: "Canada",
    flag: "https://i.ibb.co/5WNh9wm/bd-Country-Flag.png",
    data: "20GB",
    validity: "45 days",
    price: 28.8,
    facilities: ["Data Only", "No Contracts", "No SIM Cards"],
  },
  {
    area: "Coverage",
    country: "Canada",
    flag: "https://i.ibb.co/5WNh9wm/bd-Country-Flag.png",
    data: "30GB",
    validity: "60 days",
    price: 35.1,
    facilities: ["Data Only", "No Contracts", "No SIM Cards"],
  },
  {
    area: "Coverage",
    country: "Canada",
    flag: "https://i.ibb.co/5WNh9wm/bd-Country-Flag.png",
    data: "40GB",
    validity: "60 days",
    price: 42.4,
    facilities: ["Data Only", "No Contracts", "No SIM Cards"],
  },
  {
    area: "Coverage",
    country: "Canada",
    flag: "https://i.ibb.co/5WNh9wm/bd-Country-Flag.png",
    data: "50GB",
    validity: "90 days",
    price: 49.7,
    facilities: ["Data Only", "No Contracts", "No SIM Cards"],
  },
  {
    area: "Coverage",
    country: "Canada",
    flag: "https://i.ibb.co/5WNh9wm/bd-Country-Flag.png",
    data: "60GB",
    validity: "90 days",
    price: 56.0,
    facilities: ["Data Only", "No Contracts", "No SIM Cards"],
  },
  {
    area: "Coverage",
    country: "Canada",
    flag: "https://i.ibb.co/5WNh9wm/bd-Country-Flag.png",
    data: "Unlimited",
    validity: "365 days",
    price: 70.0,
    facilities: ["Data Only", "No Contracts", "No SIM Cards"],
  },
];

export default packageData;
